[package]
name = "formally-smt"
description = "the open-source formal methods toolchain - SMT abstraction layer"
homepage = "https://formally.fm"
repository = "https://github.com/formally-fm/formally"
version = "0.2025.121"
edition = "2024"
license-file = "LICENSE.txt"
readme = "README.md"
categories = [ "mathematics" ]
keywords = [ "formal-methods", "smt" ]

[lib]
crate-type = ["lib"]
path = "src/lib.rs"

[features]
default = []
__subcratedoc = []

[dependencies]
formally-support = { path = "../support", version = "0.2025.12" }
formally-io = { path = "../io", version = "0.2025.12" }
formally-smt-macros = { path = "../smt-macros", version = "0.2025.121", features = ["__subcratedoc"] }

derive_more = { version = "2.0.1", features = ["from", "as_ref", "display", "deref"] }
itertools = "0.14.0"
paste = "1.0.15"
rpds = "1"
rug = "1"
transitive = "1.2.0"
z3-sys = "0.10.0"
linkme = "0.3.35"
thiserror = "2.0.17"
