[package]
name = "formally-smt"
description = "the open-source formal methods toolchain - SMT abstraction layer"
homepage = "https://formally.fm"
repository = "https://github.com/formally-fm/formally"
version = "0.2.0"
edition = "2024"
license-file = "LICENSE.txt"
readme = "README.md"
categories = [ "mathematics" ]
keywords = [ "formal-methods", "smt" ]

[lib]
crate-type = ["lib"]
path = "src/lib.rs"

[features]
z3 = ["z3-sys"]
cvc5 = ["cvc5-sys"]
default = ["z3", "cvc5"]
__subcratedoc = []

[dependencies]
formally-support = { path = "../support", version = "0.2.0" }
formally-io = { path = "../io", version = "0.2.0" }
formally-smt-macros = { path = "../smt-macros", version = "0.2.0", features = ["__subcratedoc"] }

z3-sys = { version = "0.12.0", optional = true }
cvc5-sys = { version = "0.4.0", optional = true }

derive_more = { version = "2", features = ["from", "as_ref", "display", "deref"] }
itertools = "0.15.0"
paste = "1.0.15"
rug = "1"
transitive = "1.2.0"
linkme = "0.3.37"
thiserror = "2.0.17"
dashmap = "6.2.1"
rpds = "1"

[dev-dependencies]
rstest = "0.26.0"