[package]
name = "formally-support"
description = "the open-source formal methods toolchain - basic support functionality"
homepage = "https://formally.fm"
repository = "https://github.com/formally-fm/formally"
version = "0.2025.12"
edition = "2024"
license-file = "LICENSE.txt"
readme = "README.md"
categories = [ "mathematics" ]
keywords = [ "formal-methods" ]

[features]
default = []
__subcratedoc = []

[dependencies]
formally-support-macros = { path = "../support-macros", version = "0.2025.12", features = ["__subcratedoc"] }

dashmap = "6.1.0"
perfect-derive = "0.1.5"
derive_more = { version = "2.0.1", features = ["from", "as_ref", "display"] }
rpds = "1"
thiserror = "2.0.17"
itertools = "0.14.0"

[dev-dependencies]
formally-smt = { path = "../smt" }
