[package]
name = "formally"
description = "the open-source formal methods toolchain"
homepage = "https://formally.fm"
repository = "https://github.com/formally-fm/formally"
version = "0.2025.121"
edition = "2024"
license-file = "LICENSE.txt"
readme = "README.md"
categories = [ "mathematics" ]
keywords = [ "formal-methods", "smt" ]

[dependencies]
formally-support = { path = "../support", version = "0.2025.121", features = ["__subcratedoc"] }
formally-io = { path = "../io", version = "0.2025.12", optional = true, features = ["__subcratedoc"] }
formally-smt = { path = "../smt", version = "0.2025.121", optional = true, features = ["__subcratedoc"] }
document-features = "0.2.12"

[features]
#! This project has the following Cargo features:
default = ["io", "smt", "smt-z3", "smt-cvc5"]
## Enable the [formally::io] module.
io = ["formally-io"]
## Enable the [formally::smt] module.
smt = ["io", "formally-smt"]
## Enable the Z3 backend for the [formally::smt] module.
smt-z3 = ["formally-smt/z3"]
## Enable the cvc5 backend for the [formally::smt] module.
smt-cvc5 = ["formally-smt/cvc5"]

[dev-dependencies]
rstest = "0.26.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]